version: '3'
services:
  redis:
    image: redis
    restart: always
    command: --port 6380
    expose:
      - 6380

  elasticsearch:
    image: elasticsearch:7.17.3
    expose:
      - 9201
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms200m -Xmx200m
      http.port: 9201

  api:
    build: .
    expose:
      - 8003
    entrypoint: ["gunicorn", "main:app", "--workers", "4", "--worker-class",
                 "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8003"]
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
      - redis

  nginx:
    image: nginx:1.21.6-alpine
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - api
    ports:
      - "80:80"
volumes:
  cache:
    driver: local
