version: '3.3'

services:
  elasticsearch:
    image: elasticsearch:7.7.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  kibana:
    image: kibana:7.7.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  
  api:
    build: .
    expose:
      - "8000"
    entrypoint: ["gunicorn", "main:app", "--workers", "4", "--worker-class",
                 "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
    environment:
      - REDIS_HOST=redis
      - ES_HOST=elasticsearch
    depends_on:
      - elasticsearch
      - redis
  
  test:
    build:
      context: .
      dockerfile: Dockerfile.tests
    entrypoint: >
      sh -c "python tests/functional/utils/wait_for_es.py
      && python tests/functional/utils/wait_for_redis.py
      && cd tests
      && pytest"
    depends_on:
      - api



