FROM python:3.9.7

WORKDIR /code

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY tests/requirements.txt tests/requirements.txt
RUN pip install --upgrade pip && pip install -r tests/requirements.txt --no-cache-dir

COPY . .
