version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./admin_panel/.env
    expose:
      - 5432

  admin:
    build:
      context: ./admin_panel/
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ./admin_panel/.env
    expose:
      - 8001

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./admin_panel/static/:/data/static/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - admin
    ports:
      - 80:80
