version: '3'

services:
  auth_service_tests:
    build:
      context: .
      dockerfile: src/tests/Dockerfile
    container_name: auth_service_tests
    volumes:
      - ./src:/usr/app/
    depends_on:
      - redis_auth
      - auth_service
      - postgres_auth

  redis_auth:
    build:
      context: .
      dockerfile: ./redis/Dockerfile
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    container_name: redis
    env_file:
      - ./redis/.env

  postgres_auth:
      build:
        context: .
        dockerfile: ./postgres/Dockerfile
      container_name: postgres_auth
      restart: always
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - '5432:5432'
      expose:
        - '5432'
      env_file:
        - ./postgres/.env

  auth_service:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: auth_service
    env_file:
      - ./src/.env
    volumes:
      - ./src/:/usr/app/

volumes:
  postgres_data: