version: '3'

services:
  stat_service:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: stat_service
    volumes:
      - ./src/:/usr/app/
      - static_files:/usr/app/staticfiles
    ports:
      - '8000:8000'
    networks:
      - common-network

  nginx_stat_service:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: nginx_stat_service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_files:/home/app/staticfiles
    depends_on:
      - stat_service
    ports:
      - '81:81'
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  static_files: