"""empty message

Revision ID: 32493aed6b22
Revises: 817e72d91db4
Create Date: 2022-06-07 17:19:46.324142

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32493aed6b22'
down_revision = '817e72d91db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('internal_user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('provider', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['internal_user_id'], ['users.id'], ),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('internal_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_users')
    # ### end Alembic commands ###
